/**
 * Cloudflare Pages Function — /go/{slug}
 *
 * Overrides the static stub generated by Astro at build time.
 * On every request:
 *   1. Resolve slug → target URL + campaign meta
 *   2. Log click_event to D1
 *   3. 302 redirect to target with cache headers
 *
 * Source of truth for affiliate links: src/content/affiliate-links/*.yaml
 * At build time, we generate dist/.affiliate-links.json. This function reads
 * from KV (production) or fallback to the static JSON.
 */

interface Env {
  DB: D1Database;
  AFFILIATE_LINKS_KV?: KVNamespace;
}

interface LinkRecord {
  target_url: string;
  network?: string;
  campaign_id?: string;
  active: boolean;
}

// Embedded fallback — kept minimal; production should populate KV from build pipeline.
const FALLBACK_LINKS: Record<string, LinkRecord> = {
  // Populated by scripts/build-affiliate-links.ts at build time.
};

export const onRequest: PagesFunction<Env> = async (context) => {
  const { request, env, params } = context;
  const slug = Array.isArray(params.slug) ? params.slug[0] : (params.slug as string);

  if (!slug) {
    return new Response('Missing slug', { status: 400 });
  }

  // Resolve link
  let link: LinkRecord | null = null;
  if (env.AFFILIATE_LINKS_KV) {
    const raw = await env.AFFILIATE_LINKS_KV.get(slug, 'json');
    if (raw) link = raw as LinkRecord;
  }
  if (!link && FALLBACK_LINKS[slug]) {
    link = FALLBACK_LINKS[slug];
  }

  if (!link || !link.active) {
    return new Response('Affiliate link not found or inactive', {
      status: 404,
      headers: { 'cache-control': 'no-store' },
    });
  }

  // Parse UTM
  const url = new URL(request.url);
  const utm = {
    source: url.searchParams.get('utm_source') ?? null,
    medium: url.searchParams.get('utm_medium') ?? null,
    campaign: url.searchParams.get('utm_campaign') ?? null,
  };

  // Lightweight bot detection
  const ua = request.headers.get('user-agent') ?? '';
  const isBot = /bot|crawler|spider|crawling/i.test(ua) ? 1 : 0;

  // Log to D1 (fire and forget — don't block redirect)
  try {
    context.waitUntil(
      env.DB.prepare(
        `INSERT INTO click_events
           (slug, target_url, network, campaign_id, referrer, user_agent, country, city,
            utm_source, utm_medium, utm_campaign, is_bot)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
        .bind(
          slug,
          link.target_url,
          link.network ?? null,
          link.campaign_id ?? null,
          request.headers.get('referer') ?? null,
          ua,
          request.cf?.country ?? null,
          request.cf?.city ?? null,
          utm.source,
          utm.medium,
          utm.campaign,
          isBot,
        )
        .run(),
    );
  } catch (err) {
    // Logging failure should never block redirect
    console.error('D1 log failed', err);
  }

  return Response.redirect(link.target_url, 302);
};
